---
abstract: 'configure Dist::Zilla like RUSSOZ'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  Test::UseAllModules: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-RUSSOZ
requires:
  Dist::Zilla: 4.102341
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::Signature: 0
  Dist::Zilla::PluginBundle::TestingMania: 0.012
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0.99
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0.01
  Pod::Weaver::Section::SeeAlso: 1.002
  Pod::Weaver::Section::Support: 1.003
  Pod::Weaver::Section::WarrantyDisclaimer: 0.103511
  namespace::autoclean: 0.09
  namespace::clean: 0
  version: 0
resources:
  homepage: https://github.com/russoz/Dist-Zilla-PluginBundle-Author-RUSSOZ
  repository: https://github.com/russoz/Dist-Zilla-PluginBundle-Author-RUSSOZ
version: 0.013
